trigger:
- main

pool:
  name: TerraformTraining

steps:

# Install Terraform
- script: |
    sudo apt-get update
    sudo apt-get install -y wget unzip
    wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
    unzip terraform_1.7.5_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

# Initialize Terraform
- script: |
    terraform init
  displayName: 'Terraform Init'

# Validate Terraform files
- script: |
    terraform validate
  displayName: 'Terraform Validate'

# Run Terraform Plan
- script: |
    terraform plan
  displayName: 'Terraform Plan'
